import AvatarNameCell from '@Components/Table/Components/AvatarNameCell/AvatarNameCell';
import BadgeNameCell from '@Components/Table/Components/BadgeNameCell/BadgeNameCell';
import DropDownCell from '@Components/Table/Components/DropDownCell/DropDownCell';
import { createSlice } from '@reduxjs/toolkit';
import Gear from 'public/Assets/Svgs/gear.svg';

const clientsSlice = createSlice({
    name: 'clients',
    initialState: {
        addClientDialog: false,
        importClientsDialog: false,
        columns: [
            {
                field: 'settings',
                headerName: (
                    <Gear
                        color={"#ACADAF"}
                        height={15}
                        width={15}
                    />
                ),
                width: 50,
                headerClassName: 'settings-header',
                sortable: false,
            },
            {
                field: 'id',
                headerName: 'Id',
                width: 50,
                hide: true,
                hidable: true,
            },
            {
                field: 'clientName',
                headerName: 'Client Name',
                width: 200,
                headerClassName: 'separator-header',
                hidable: true,
                renderCell: (props) => (
                    <BadgeNameCell
                        {...props}
                        navigateTo="client-dashboard"
                    />
                ),
                hide: false,
            },
            {
                field: 'email',
                headerName: 'Email',
                width: 200,
                headerClassName: 'separator-header',
                hidable: true,
            },
            {
                field: 'mobile',
                headerName: 'Mobile',
                width: 200,
                headerClassName: 'separator-header',
                hidable: true,
            },
            {
                field: 'pfp',
                headerName: 'Assigned To Pfp',
                width: 200,
                hide: true,
            },
            {
                field: 'assignedTo',
                headerName: 'Assigned To',
                width: 200,
                headerClassName: 'separator-header',
                hidable: true,
                renderCell: AvatarNameCell,
            },
            {
                field: 'followUp',
                headerName: 'Follow Up',
                width: 200,
                headerClassName: 'separator-header',
                hidable: true,
            },
            {
                field: 'lastLogin',
                headerName: 'Last Login',
                width: 200,
                headerClassName: 'separator-header',
                hidable: true,
            },
            {
                field: 'status',
                headerName: 'Status',
                width: 200,
                hidable: true,
                editable: true,
                type: 'singleSelect',
                valueOptions: ['Lead', 'Active', 'Inactive', 'Cancelled'],
                renderCell: ({ value }) => <DropDownCell value={value} />,
            },
        ],
        clients: [
            {
                id: 1,
                clientName: 'Zeeshan Ahmad',
                email: 'zak@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/d-ace.jpg',
                assignedTo: 'd ace',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Lead',
            },
            {
                id: 2,
                clientName: 'Rafay',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/d-water-law.jpg',
                assignedTo: 'd water law',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Active',
            },
            {
                id: 3,
                clientName: 'Ali',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/d-luffy.jpg',
                assignedTo: 'd luffy',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Inactive',
            },
            {
                id: 4,
                clientName: 'Usman',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/kaido.jpg',
                assignedTo: 'kaido',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Cancelled',
            },
            {
                id: 5,
                clientName: 'Mudasir',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/nami.jpg',
                assignedTo: 'nami',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Inactive',
            },
            {
                id: 6,
                clientName: 'Qammar Jamshaid',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/nico-robin.jpg',
                assignedTo: 'nico robin',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Active',
            },
            {
                id: 7,
                clientName: 'Usama',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/roronoa-zoro.jpg',
                assignedTo: 'roronoa zoro',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Active',
            },
            {
                id: 8,
                clientName: 'Haris',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/shanks.jpg',
                assignedTo: 'shanks',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Cancelled',
            },
            {
                id: 9,
                clientName: 'Showkat',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/tony-tony-chopper.jpg',
                assignedTo: 'tony tony chopper',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Cancelled',
            },
            {
                id: 10,
                clientName: 'Awais',
                email: 'John@gmail.com',
                mobile: '(000) 000 - 0000',
                pfp: '/Assets/Images/vinsmoke-sanji.jpg',
                assignedTo: 'vinsmoke sanji',
                followUp: '12/02/2022',
                lastLogin: 'June 22, 12:20 PM',
                status: 'Cancelled',
            },
        ],
        defaultColumns: [
            "settings",
            "clientName",
            "email",
            "mobile",
            "assignedTo",
            "followUp",
            "lastLogin",
            "status",
        ],
        cities: [
            { label: "Abbeville", value: 1 },
            { label: "Adamsville", value: 2 },
            { label: "Addison", value: 3 },
            { label: "Akron", value: 4 },
            { label: "Alabaster", value: 5 },
            { label: "Albertville", value: 6 },
            { label: "Alexander", value: 7 },
            { label: "Aliceville", value: 8 },
            { label: "Allgood", value: 9 },
            { label: "Altoona", value: 10 },
            { label: "Andalusia", value: 11 },
            { label: "Anderson", value: 12 },
            { label: "Anniston", value: 13 },
            { label: "Arab", value: 14 },
            { label: "Ardmore", value: 15 },
            { label: "Argo", value: 16 },
            { label: "Ariton", value: 17 },
            { label: "Arley", value: 18 },
            { label: "Ashford", value: 19 },
            { label: "Ashland", value: 20 },
            { label: "Ashville", value: 21 },
            { label: "Athens", value: 22 },
            { label: "Atmore", value: 23 },
            { label: "Attalla", value: 24 },
            { label: "Auburn", value: 25 },
            { label: "Autaugaville", value: 26 },
            { label: "Avon", value: 27 },
            { label: "Babbie", value: 28 },
            { label: "Baileyton", value: 29 },
            { label: "Bakerhill", value: 30 },
            { label: "Banks", value: 31 },
            { label: "Bay Minette", value: 32 },
            { label: "Bayou La Batre", value: 33 },
            { label: "Bear Creek", value: 34 },
            { label: "Beatrice", value: 35 },
            { label: "Beaverton", value: 36 },
            { label: "Belk", value: 37 },
            { label: "Benton", value: 38 },
            { label: "Berry", value: 39 },
            { label: "Bessemer", value: 40 },
            { label: "Billingsley", value: 41 },
            { label: "Birmingham", value: 42 },
            { label: "Black", value: 43 },
            { label: "Blountsville", value: 44 },
            { label: "Blue Springs", value: 45 },
            { label: "Boaz", value: 46 },
            { label: "Boligee", value: 47 },
            { label: "Bon Air", value: 48 },
            { label: "Brantley", value: 49 },
            { label: "Brent", value: 50 },
            { label: "Brewton", value: 51 },
            { label: "Bridgeport", value: 52 },
            { label: "Brighton", value: 53 },
            { label: "Brilliant", value: 54 },
            { label: "Brookside", value: 55 },
            { label: "Brookwood", value: 56 },
            { label: "Brundidge", value: 57 },
            { label: "Butler", value: 58 },
            { label: "Calera", value: 59 },
            { label: "Camden", value: 60 },
            { label: "Camp Hill", value: 61 },
            { label: "Carbon Hill", value: 62 },
            { label: "Cardiff", value: 63 },
            { label: "Carolina", value: 64 },
            { label: "Carrollton", value: 65 },
            { label: "Castleberry", value: 66 },
            { label: "Cedar Bluff", value: 67 },
            { label: "Center Point", value: 68 },
            { label: "Centre", value: 69 },
            { label: "Centreville", value: 70 },
            { label: "Chatom", value: 71 },
            { label: "Chelsea", value: 72 },
            { label: "Cherokee", value: 73 },
            { label: "Chickasaw", value: 74 },
            { label: "Childersburg", value: 75 },
            { label: "Citronelle", value: 76 },
            { label: "Clanton", value: 77 },
            { label: "Clay", value: 78 },
            { label: "Clayhatchee", value: 79 },
            { label: "Clayton", value: 80 },
            { label: "Cleveland", value: 81 },
            { label: "Clio", value: 82 },
            { label: "Coaling", value: 83 },
            { label: "Coffee Springs", value: 84 },
            { label: "Coffeeville", value: 85 },
            { label: "Coker", value: 86 },
            { label: "Collinsville", value: 87 },
            { label: "Colony", value: 88 },
            { label: "Columbia", value: 89 },
            { label: "Columbiana", value: 90 },
            { label: "Coosada", value: 91 },
            { label: "Cordova", value: 92 },
            { label: "Cottonwood", value: 93 },
            { label: "County Line", value: 94 },
            { label: "Courtland", value: 95 },
            { label: "Cowarts", value: 96 },
            { label: "Creola", value: 97 },
            { label: "Crossville", value: 98 },
            { label: "Cuba", value: 99 },
            { label: "Cullman", value: 100 },
            { label: "Cusseta", value: 101 },
            { label: "Dadeville", value: 102 },
            { label: "Daleville", value: 103 },
            { label: "Daphne", value: 104 },
            { label: "Dauphin Island", value: 105 },
            { label: "Daviston", value: 106 },
            { label: "Dayton", value: 107 },
            { label: "Deatsville", value: 108 },
            { label: "Decatur", value: 109 },
            { label: "Demopolis", value: 110 },
            { label: "Detroit", value: 111 },
            { label: "Dodge City", value: 112 },
            { label: "Dora", value: 113 },
            { label: "Dothan", value: 114 },
            { label: "Double Springs", value: 115 },
            { label: "Douglas", value: 116 },
            { label: "Dozier", value: 117 },
            { label: "Dutton", value: 118 },
            { label: "East Brewton", value: 119 },
            { label: "Eclectic", value: 120 },
            { label: "Edwardsville", value: 121 },
            { label: "Elba", value: 122 },
            { label: "Elberta", value: 123 },
            { label: "Eldridge", value: 124 },
            { label: "Elkmont", value: 125 },
            { label: "Elmore", value: 126 },
            { label: "Emelle", value: 127 },
            { label: "Enterprise", value: 128 },
            { label: "Epes", value: 129 },
            { label: "Ethelsville", value: 130 },
            { label: "Eufaula", value: 131 },
            { label: "Eutaw", value: 132 },
            { label: "Eva", value: 133 },
            { label: "Evergreen", value: 134 },
            { label: "Excel", value: 135 },
            { label: "Fairfield", value: 136 },
            { label: "Fairhope", value: 137 },
            { label: "Fairview", value: 138 },
            { label: "Falkville", value: 139 },
            { label: "Faunsdale", value: 140 },
            { label: "Fayette", value: 141 },
            { label: "Five Points", value: 142 },
            { label: "Flomaton", value: 143 },
            { label: "Florala", value: 144 },
            { label: "Florence", value: 145 },
            { label: "Foley", value: 146 },
            { label: "Forkland", value: 147 },
            { label: "Fort Deposit", value: 148 },
            { label: "Fort Payne", value: 149 },
            { label: "Franklin", value: 150 },
            { label: "Frisco City", value: 151 },
            { label: "Fruithurst", value: 152 },
            { label: "Fulton", value: 153 },
            { label: "Fultondale", value: 154 },
            { label: "Fyffe", value: 155 },
            { label: "Gadsden", value: 156 },
            { label: "Gainesville", value: 157 },
            { label: "Gantt", value: 158 },
            { label: "Garden City", value: 159 },
            { label: "Gardendale", value: 160 },
            { label: "Gaylesville", value: 161 },
            { label: "Geiger", value: 162 },
            { label: "Geneva", value: 163 },
            { label: "Georgiana", value: 164 },
            { label: "Geraldine", value: 165 },
            { label: "Gilbertown", value: 166 },
            { label: "Glen Allen", value: 167 },
            { label: "Glencoe", value: 168 },
            { label: "Glenwood", value: 169 },
            { label: "Goldville", value: 170 },
            { label: "Good Hope", value: 171 },
            { label: "Goodwater", value: 172 },
            { label: "Gordo", value: 173 },
            { label: "Gordon", value: 174 },
            { label: "Gordonville", value: 175 },
            { label: "Goshen", value: 176 },
            { label: "Grant", value: 177 },
            { label: "Graysville", value: 178 },
            { label: "Greensboro", value: 179 },
            { label: "Greenville", value: 180 },
            { label: "Grimes", value: 181 },
            { label: "Grove Hill", value: 182 },
            { label: "Guin", value: 183 },
            { label: "Gulf Shores", value: 184 },
            { label: "Guntersville", value: 185 },
            { label: "Gurley", value: 186 },
            { label: "Gu-Win", value: 187 },
            { label: "Hackleburg", value: 188 },
            { label: "Haleburg", value: 189 },
            { label: "Haleyville", value: 190 },
            { label: "Hamilton", value: 191 },
            { label: "Hammondville", value: 192 },
            { label: "Hanceville", value: 193 },
            { label: "Harpersville", value: 194 },
            { label: "Hartford", value: 195 },
            { label: "Hartselle", value: 196 },
            { label: "Hayden", value: 197 },
            { label: "Hayneville", value: 198 },
            { label: "Headland", value: 199 },
            { label: "Heath", value: 200 },
            { label: "Heflin", value: 201 },
            { label: "Helena", value: 202 },
            { label: "Henagar", value: 203 },
            { label: "Highland Lake", value: 204 },
            { label: "Hillsboro", value: 205 },
            { label: "Hobson City", value: 206 },
            { label: "Hodges", value: 207 },
            { label: "Hokes Bluff", value: 208 },
            { label: "Holly Pond", value: 209 },
            { label: "Hollywood", value: 210 },
            { label: "Homewood", value: 211 },
            { label: "Hoover", value: 212 },
            { label: "Horn Hill", value: 213 },
            { label: "Hueytown", value: 214 },
            { label: "Huntsville", value: 215 },
            { label: "Hurtsboro", value: 216 },
            { label: "Hytop", value: 217 },
            { label: "Ider", value: 218 },
            { label: "Indian Springs Village", value: 219 },
            { label: "Irondale", value: 220 },
            { label: "Jackson", value: 221 },
            { label: "Jackson's Gap", value: 222 },
            { label: "Jacksonville", value: 223 },
            { label: "Jasper", value: 224 },
            { label: "Jemison", value: 225 },
            { label: "Kansas", value: 226 },
            { label: "Kellyton", value: 227 },
            { label: "Kennedy", value: 228 },
            { label: "Killen", value: 229 },
            { label: "Kimberly", value: 230 },
            { label: "Kinsey", value: 231 },
            { label: "Kinston", value: 232 },
            { label: "LaFayette", value: 233 },
            { label: "Lake View", value: 234 },
            { label: "Lakeview", value: 235 },
            { label: "Lanett", value: 236 },
            { label: "Langston", value: 237 },
            { label: "Leeds", value: 238 },
            { label: "Leesburg", value: 239 },
            { label: "Leighton", value: 240 },
            { label: "Lester", value: 241 },
            { label: "Level Plains", value: 242 },
            { label: "Lexington", value: 243 },
            { label: "Libertyville", value: 244 },
            { label: "Lincoln", value: 245 },
            { label: "Linden", value: 246 },
            { label: "Lineville", value: 247 },
            { label: "Lipscomb", value: 248 },
            { label: "Lisman", value: 249 },
            { label: "Littleville", value: 250 },
            { label: "Livingston", value: 251 },
            { label: "Loachapoka", value: 252 },
            { label: "Lockhart", value: 253 },
            { label: "Locust Fork", value: 254 },
            { label: "Louisville", value: 255 },
            { label: "Lowndesboro", value: 256 },
            { label: "Loxley", value: 257 },
            { label: "Luverne", value: 258 },
            { label: "Lynn", value: 259 },
            { label: "Madison", value: 260 },
            { label: "Madrid", value: 261 },
            { label: "Magnolia Springs", value: 262 },
            { label: "Malvern", value: 263 },
            { label: "Maplesville", value: 264 },
            { label: "Margaret", value: 265 },
            { label: "Marion", value: 266 },
            { label: "Maytown", value: 267 },
            { label: "McIntosh", value: 268 },
            { label: "McKenzie", value: 269 },
            { label: "McMullen", value: 270 },
            { label: "Memphis", value: 271 },
            { label: "Mentone", value: 272 },
            { label: "Midfield", value: 273 },
            { label: "Midland City", value: 274 },
            { label: "Midway", value: 275 },
            { label: "Millbrook", value: 276 },
            { label: "Millport", value: 277 },
            { label: "Millry", value: 278 },
            { label: "Mobile", value: 279 },
            { label: "Monroeville", value: 280 },
            { label: "Montevallo", value: 281 },
            { label: "Montgomery", value: 282 },
            { label: "Moody", value: 283 },
            { label: "Mooresville", value: 284 },
            { label: "Morris", value: 285 },
            { label: "Mosses", value: 286 },
            { label: "Moulton", value: 287 },
            { label: "Moundville", value: 288 },
            { label: "Mount Vernon", value: 289 },
            { label: "Mountain Brook", value: 290 },
            { label: "Mulga", value: 291 },
            { label: "Munford", value: 292 },
            { label: "Muscle Shoals", value: 293 },
            { label: "Myrtlewood", value: 294 },
            { label: "Napier Field", value: 295 },
            { label: "Natural Bridge", value: 296 },
            { label: "Nauvoo", value: 297 },
            { label: "Nectar", value: 298 },
            { label: "Needham", value: 299 },
            { label: "New Brockton", value: 300 },
            { label: "New Hope", value: 301 },
            { label: "New Site", value: 302 },
            { label: "Newbern", value: 303 },
            { label: "Newton", value: 304 },
            { label: "Newville", value: 305 },
            { label: "North Courtland", value: 306 },
            { label: "North Johns", value: 307 },
            { label: "Northport", value: 308 },
            { label: "Notasulga", value: 309 },
            { label: "Oak Grove", value: 310 },
            { label: "Oak Hill", value: 311 },
            { label: "Oakman", value: 312 },
            { label: "Odenville", value: 313 },
            { label: "Ohatchee", value: 314 },
            { label: "Oneonta", value: 315 },
            { label: "Onycha", value: 316 },
            { label: "Opelika", value: 317 },
            { label: "Opp", value: 318 },
            { label: "Orange Beach", value: 319 },
            { label: "Orrville", value: 320 },
            { label: "Owens Cross Roads", value: 321 },
            { label: "Oxford", value: 322 },
            { label: "Ozark", value: 323 },
            { label: "Paint Rock", value: 324 },
            { label: "Parrish", value: 325 },
            { label: "Pelham", value: 326 },
            { label: "Pell City", value: 327 },
            { label: "Pennington", value: 328 },
            { label: "Perdido Beach", value: 329 },
            { label: "Petrey", value: 330 },
            { label: "Phenix City", value: 331 },
            { label: "Phil Campbell", value: 332 },
            { label: "Pickensville", value: 333 },
            { label: "Piedmont", value: 334 },
            { label: "Pike Road", value: 335 },
            { label: "Pinckard", value: 336 },
            { label: "Pine Apple", value: 337 },
            { label: "Pine Hill", value: 338 },
            { label: "Pine Ridge", value: 339 },
            { label: "Pinson", value: 340 },
            { label: "Pisgah", value: 341 },
            { label: "Pleasant Grove", value: 342 },
            { label: "Pleasant Groves", value: 343 },
            { label: "Pollard", value: 344 },
            { label: "Powell", value: 345 },
            { label: "Prattville", value: 346 },
            { label: "Priceville", value: 347 },
            { label: "Prichard", value: 348 },
            { label: "Providence", value: 349 },
            { label: "Ragland", value: 350 },
            { label: "Rainbow City", value: 351 },
            { label: "Rainsville", value: 352 },
            { label: "Ranburne", value: 353 },
            { label: "Red Bay", value: 354 },
            { label: "Red Level", value: 355 },
            { label: "Reece City", value: 356 },
            { label: "Reform", value: 357 },
            { label: "Rehobeth", value: 358 },
            { label: "Repton", value: 359 },
            { label: "Ridgeville", value: 360 },
            { label: "River Falls", value: 361 },
            { label: "Riverside", value: 362 },
            { label: "Riverview", value: 363 },
            { label: "Roanoke", value: 364 },
            { label: "Robertsdale", value: 365 },
            { label: "Rockford", value: 366 },
            { label: "Rogersville", value: 367 },
            { label: "Rosa", value: 368 },
            { label: "Russellville", value: 369 },
            { label: "Rutledge", value: 370 },
            { label: "St. Florian", value: 371 },
            { label: "Samson", value: 372 },
            { label: "Sand Rock", value: 373 },
            { label: "Sanford", value: 374 },
            { label: "Saraland", value: 375 },
            { label: "Sardis City", value: 376 },
            { label: "Satsuma", value: 377 },
            { label: "Scottsboro", value: 378 },
            { label: "Section", value: 379 },
            { label: "Selma", value: 380 },
            { label: "Sheffield", value: 381 },
            { label: "Shiloh", value: 382 },
            { label: "Shorter", value: 383 },
            { label: "Silas", value: 384 },
            { label: "Silverhill", value: 385 },
            { label: "Sipsey", value: 386 },
            { label: "Skyline", value: 387 },
            { label: "Slocomb", value: 388 },
            { label: "Smiths Station", value: 389 },
            { label: "Snead", value: 390 },
            { label: "Somerville", value: 391 },
            { label: "South Vinemont", value: 392 },
            { label: "Southside", value: 393 },
            { label: "Spanish Fort", value: 394 },
            { label: "Springville", value: 395 },
            { label: "Steele", value: 396 },
            { label: "Stevenson", value: 397 },
            { label: "Sulligent", value: 398 },
            { label: "Sumiton", value: 399 },
            { label: "Summerdale", value: 400 },
            { label: "Susan Moore", value: 401 },
            { label: "Sweet Water", value: 402 },
            { label: "Sylacauga", value: 403 },
            { label: "Sylvan Springs", value: 404 },
            { label: "Sylvania", value: 405 },
            { label: "Talladega Springs", value: 406 },
            { label: "Talladega", value: 407 },
            { label: "Tallassee", value: 408 },
            { label: "Tarrant", value: 409 },
            { label: "Taylor", value: 410 },
            { label: "Thomaston", value: 411 },
            { label: "Thomasville", value: 412 },
            { label: "Thorsby", value: 413 },
            { label: "Town Creek", value: 414 },
            { label: "Toxey", value: 415 },
            { label: "Trafford", value: 416 },
            { label: "Triana", value: 417 },
            { label: "Trinity", value: 418 },
            { label: "Troy", value: 419 },
            { label: "Trussville", value: 420 },
            { label: "Tuscaloosa", value: 421 },
            { label: "Tuscumbia", value: 422 },
            { label: "Tuskegee", value: 423 },
            { label: "Twin", value: 424 },
            { label: "Union Grove", value: 425 },
            { label: "Union Springs", value: 426 },
            { label: "Union", value: 427 },
            { label: "Uniontown", value: 428 },
            { label: "Valley", value: 429 },
            { label: "Valley Grande", value: 430 },
            { label: "Valley Head", value: 431 },
            { label: "Vance", value: 432 },
            { label: "Vernon", value: 433 },
            { label: "Vestavia Hills", value: 434 },
            { label: "Vina", value: 435 },
            { label: "Vincent", value: 436 },
            { label: "Vredenburgh", value: 437 },
            { label: "Wadley", value: 438 },
            { label: "Waldo", value: 439 },
            { label: "Walnut Grove", value: 440 },
            { label: "Warrior", value: 441 },
            { label: "Waterloo", value: 442 },
            { label: "Waverly", value: 443 },
            { label: "Weaver", value: 444 },
            { label: "Webb", value: 445 },
            { label: "Wedowee", value: 446 },
            { label: "West Blocton", value: 447 },
            { label: "West Jefferson", value: 448 },
            { label: "West Point", value: 449 },
            { label: "Westover", value: 450 },
            { label: "Wetumpka", value: 451 },
            { label: "White Hall", value: 452 },
            { label: "Wilsonville", value: 453 },
            { label: "Wilton", value: 454 },
            { label: "Winfield", value: 455 },
            { label: "Woodland", value: 456 },
            { label: "Woodstock", value: 457 },
            { label: "Woodville", value: 458 },
            { label: "Yellow Bluff", value: 459 },
            { label: "York", value: 460 },
        ],
        states: [
            { label: "Alabama", value: "AL", },
            { label: "Alaska", value: "AK", },
            { label: "American Samoa", value: "AS", },
            { label: "Arizona", value: "AZ", },
            { label: "Arkansas", value: "AR", },
            { label: "California", value: "CA", },
            { label: "Colorado", value: "CO", },
            { label: "Connecticut", value: "CT", },
            { label: "Delaware", value: "DE", },
            { label: "District Of Columbia", value: "DC", },
            { label: "Federated States Of Micronesia", value: "FM", },
            { label: "Florida", value: "FL", },
            { label: "Georgia", value: "GA", },
            { label: "Guam", value: "GU", },
            { label: "Hawaii", value: "HI", },
            { label: "Idaho", value: "ID", },
            { label: "Illinois", value: "IL", },
            { label: "Indiana", value: "IN", },
            { label: "Iowa", value: "IA", },
            { label: "Kansas", value: "KS", },
            { label: "Kentucky", value: "KY", },
            { label: "Louisiana", value: "LA", },
            { label: "Maine", value: "ME", },
            { label: "Marshall Islands", value: "MH", },
            { label: "Maryland", value: "MD", },
            { label: "Massachusetts", value: "MA", },
            { label: "Michigan", value: "MI", },
            { label: "Minnesota", value: "MN", },
            { label: "Mississippi", value: "MS", },
            { label: "Missouri", value: "MO", },
            { label: "Montana", value: "MT", },
            { label: "Nebraska", value: "NE", },
            { label: "Nevada", value: "NV", },
            { label: "New Hampshire", value: "NH", },
            { label: "New Jersey", value: "NJ", },
            { label: "New Mexico", value: "NM", },
            { label: "New York", value: "NY", },
            { label: "North Carolina", value: "NC", },
            { label: "North Dakota", value: "ND", },
            { label: "Northern Mariana Islands", value: "MP", },
            { label: "Ohio", value: "OH", },
            { label: "Oklahoma", value: "OK", },
            { label: "Oregon", value: "OR", },
            { label: "Palau", value: "PW", },
            { label: "Pennsylvania", value: "PA", },
            { label: "Puerto Rico", value: "PR", },
            { label: "Rhode Island", value: "RI", },
            { label: "South Carolina", value: "SC", },
            { label: "South Dakota", value: "SD", },
            { label: "Tennessee", value: "TN", },
            { label: "Texas", value: "TX", },
            { label: "Utah", value: "UT", },
            { label: "Vermont", value: "VT", },
            { label: "Virgin Islands", value: "VI", },
            { label: "Virginia", value: "VA", },
            { label: "Washington", value: "WA", },
            { label: "West Virginia", value: "WV", },
            { label: "Wisconsin", value: "WI", },
            { label: "Wyoming", value: "WY", }
        ],
        countries: [
            { label: 'Afghanistan', value: 'AF' },
            { label: 'Åland Islands', value: 'AX' },
            { label: 'Albania', value: 'AL' },
            { label: 'Algeria', value: 'DZ' },
            { label: 'American Samoa', value: 'AS' },
            { label: 'AndorrA', value: 'AD' },
            { label: 'Angola', value: 'AO' },
            { label: 'Anguilla', value: 'AI' },
            { label: 'Antarctica', value: 'AQ' },
            { label: 'Antigua and Barbuda', value: 'AG' },
            { label: 'Argentina', value: 'AR' },
            { label: 'Armenia', value: 'AM' },
            { label: 'Aruba', value: 'AW' },
            { label: 'Australia', value: 'AU' },
            { label: 'Austria', value: 'AT' },
            { label: 'Azerbaijan', value: 'AZ' },
            { label: 'Bahamas', value: 'BS' },
            { label: 'Bahrain', value: 'BH' },
            { label: 'Bangladesh', value: 'BD' },
            { label: 'Barbados', value: 'BB' },
            { label: 'Belarus', value: 'BY' },
            { label: 'Belgium', value: 'BE' },
            { label: 'Belize', value: 'BZ' },
            { label: 'Benin', value: 'BJ' },
            { label: 'Bermuda', value: 'BM' },
            { label: 'Bhutan', value: 'BT' },
            { label: 'Bolivia', value: 'BO' },
            { label: 'Bosnia and Herzegovina', value: 'BA' },
            { label: 'Botswana', value: 'BW' },
            { label: 'Bouvet Island', value: 'BV' },
            { label: 'Brazil', value: 'BR' },
            { label: 'British Indian Ocean Territory', value: 'IO' },
            { label: 'Brunei Darussalam', value: 'BN' },
            { label: 'Bulgaria', value: 'BG' },
            { label: 'Burkina Faso', value: 'BF' },
            { label: 'Burundi', value: 'BI' },
            { label: 'Cambodia', value: 'KH' },
            { label: 'Cameroon', value: 'CM' },
            { label: 'Canada', value: 'CA' },
            { label: 'Cape Verde', value: 'CV' },
            { label: 'Cayman Islands', value: 'KY' },
            { label: 'Central African Republic', value: 'CF' },
            { label: 'Chad', value: 'TD' },
            { label: 'Chile', value: 'CL' },
            { label: 'China', value: 'CN' },
            { label: 'Christmas Island', value: 'CX' },
            { label: 'Cocos (Keeling) Islands', value: 'CC' },
            { label: 'Colombia', value: 'CO' },
            { label: 'Comoros', value: 'KM' },
            { label: 'Congo', value: 'CG' },
            { label: 'Congo, The Democratic Republic of the', value: 'CD' },
            { label: 'Cook Islands', value: 'CK' },
            { label: 'Costa Rica', value: 'CR' },
            { label: 'Cote D\'Ivoire', value: 'CI' },
            { label: 'Croatia', value: 'HR' },
            { label: 'Cuba', value: 'CU' },
            { label: 'Cyprus', value: 'CY' },
            { label: 'Czech Republic', value: 'CZ' },
            { label: 'Denmark', value: 'DK' },
            { label: 'Djibouti', value: 'DJ' },
            { label: 'Dominica', value: 'DM' },
            { label: 'Dominican Republic', value: 'DO' },
            { label: 'Ecuador', value: 'EC' },
            { label: 'Egypt', value: 'EG' },
            { label: 'El Salvador', value: 'SV' },
            { label: 'Equatorial Guinea', value: 'GQ' },
            { label: 'Eritrea', value: 'ER' },
            { label: 'Estonia', value: 'EE' },
            { label: 'Ethiopia', value: 'ET' },
            { label: 'Falkland Islands (Malvinas)', value: 'FK' },
            { label: 'Faroe Islands', value: 'FO' },
            { label: 'Fiji', value: 'FJ' },
            { label: 'Finland', value: 'FI' },
            { label: 'France', value: 'FR' },
            { label: 'French Guiana', value: 'GF' },
            { label: 'French Polynesia', value: 'PF' },
            { label: 'French Southern Territories', value: 'TF' },
            { label: 'Gabon', value: 'GA' },
            { label: 'Gambia', value: 'GM' },
            { label: 'Georgia', value: 'GE' },
            { label: 'Germany', value: 'DE' },
            { label: 'Ghana', value: 'GH' },
            { label: 'Gibraltar', value: 'GI' },
            { label: 'Greece', value: 'GR' },
            { label: 'Greenland', value: 'GL' },
            { label: 'Grenada', value: 'GD' },
            { label: 'Guadeloupe', value: 'GP' },
            { label: 'Guam', value: 'GU' },
            { label: 'Guatemala', value: 'GT' },
            { label: 'Guernsey', value: 'GG' },
            { label: 'Guinea', value: 'GN' },
            { label: 'Guinea-Bissau', value: 'GW' },
            { label: 'Guyana', value: 'GY' },
            { label: 'Haiti', value: 'HT' },
            { label: 'Heard Island and Mcdonald Islands', value: 'HM' },
            { label: 'Holy See (Vatican City State)', value: 'VA' },
            { label: 'Honduras', value: 'HN' },
            { label: 'Hong Kong', value: 'HK' },
            { label: 'Hungary', value: 'HU' },
            { label: 'Iceland', value: 'IS' },
            { label: 'India', value: 'IN' },
            { label: 'Indonesia', value: 'ID' },
            { label: 'Iran, Islamic Republic Of', value: 'IR' },
            { label: 'Iraq', value: 'IQ' },
            { label: 'Ireland', value: 'IE' },
            { label: 'Isle of Man', value: 'IM' },
            { label: 'Israel', value: 'IL' },
            { label: 'Italy', value: 'IT' },
            { label: 'Jamaica', value: 'JM' },
            { label: 'Japan', value: 'JP' },
            { label: 'Jersey', value: 'JE' },
            { label: 'Jordan', value: 'JO' },
            { label: 'Kazakhstan', value: 'KZ' },
            { label: 'Kenya', value: 'KE' },
            { label: 'Kiribati', value: 'KI' },
            { label: 'Korea, Democratic People\'S Republic of', value: 'KP' },
            { label: 'Korea, Republic of', value: 'KR' },
            { label: 'Kuwait', value: 'KW' },
            { label: 'Kyrgyzstan', value: 'KG' },
            { label: 'Lao People\'S Democratic Republic', value: 'LA' },
            { label: 'Latvia', value: 'LV' },
            { label: 'Lebanon', value: 'LB' },
            { label: 'Lesotho', value: 'LS' },
            { label: 'Liberia', value: 'LR' },
            { label: 'Libyan Arab Jamahiriya', value: 'LY' },
            { label: 'Liechtenstein', value: 'LI' },
            { label: 'Lithuania', value: 'LT' },
            { label: 'Luxembourg', value: 'LU' },
            { label: 'Macao', value: 'MO' },
            { label: 'Macedonia, The Former Yugoslav Republic of', value: 'MK' },
            { label: 'Madagascar', value: 'MG' },
            { label: 'Malawi', value: 'MW' },
            { label: 'Malaysia', value: 'MY' },
            { label: 'Maldives', value: 'MV' },
            { label: 'Mali', value: 'ML' },
            { label: 'Malta', value: 'MT' },
            { label: 'Marshall Islands', value: 'MH' },
            { label: 'Martinique', value: 'MQ' },
            { label: 'Mauritania', value: 'MR' },
            { label: 'Mauritius', value: 'MU' },
            { label: 'Mayotte', value: 'YT' },
            { label: 'Mexico', value: 'MX' },
            { label: 'Micronesia, Federated States of', value: 'FM' },
            { label: 'Moldova, Republic of', value: 'MD' },
            { label: 'Monaco', value: 'MC' },
            { label: 'Mongolia', value: 'MN' },
            { label: 'Montserrat', value: 'MS' },
            { label: 'Morocco', value: 'MA' },
            { label: 'Mozambique', value: 'MZ' },
            { label: 'Myanmar', value: 'MM' },
            { label: 'Namibia', value: 'NA' },
            { label: 'Nauru', value: 'NR' },
            { label: 'Nepal', value: 'NP' },
            { label: 'Netherlands', value: 'NL' },
            { label: 'Netherlands Antilles', value: 'AN' },
            { label: 'New Caledonia', value: 'NC' },
            { label: 'New Zealand', value: 'NZ' },
            { label: 'Nicaragua', value: 'NI' },
            { label: 'Niger', value: 'NE' },
            { label: 'Nigeria', value: 'NG' },
            { label: 'Niue', value: 'NU' },
            { label: 'Norfolk Island', value: 'NF' },
            { label: 'Northern Mariana Islands', value: 'MP' },
            { label: 'Norway', value: 'NO' },
            { label: 'Oman', value: 'OM' },
            { label: 'Pakistan', value: 'PK' },
            { label: 'Palau', value: 'PW' },
            { label: 'Palestinian Territory, Occupied', value: 'PS' },
            { label: 'Panama', value: 'PA' },
            { label: 'Papua New Guinea', value: 'PG' },
            { label: 'Paraguay', value: 'PY' },
            { label: 'Peru', value: 'PE' },
            { label: 'Philippines', value: 'PH' },
            { label: 'Pitcairn', value: 'PN' },
            { label: 'Poland', value: 'PL' },
            { label: 'Portugal', value: 'PT' },
            { label: 'Puerto Rico', value: 'PR' },
            { label: 'Qatar', value: 'QA' },
            { label: 'Reunion', value: 'RE' },
            { label: 'Romania', value: 'RO' },
            { label: 'Russian Federation', value: 'RU' },
            { label: 'RWANDA', value: 'RW' },
            { label: 'Saint Helena', value: 'SH' },
            { label: 'Saint Kitts and Nevis', value: 'KN' },
            { label: 'Saint Lucia', value: 'LC' },
            { label: 'Saint Pierre and Miquelon', value: 'PM' },
            { label: 'Saint Vincent and the Grenadines', value: 'VC' },
            { label: 'Samoa', value: 'WS' },
            { label: 'San Marino', value: 'SM' },
            { label: 'Sao Tome and Principe', value: 'ST' },
            { label: 'Saudi Arabia', value: 'SA' },
            { label: 'Senegal', value: 'SN' },
            { label: 'Serbia and Montenegro', value: 'CS' },
            { label: 'Seychelles', value: 'SC' },
            { label: 'Sierra Leone', value: 'SL' },
            { label: 'Singapore', value: 'SG' },
            { label: 'Slovakia', value: 'SK' },
            { label: 'Slovenia', value: 'SI' },
            { label: 'Solomon Islands', value: 'SB' },
            { label: 'Somalia', value: 'SO' },
            { label: 'South Africa', value: 'ZA' },
            { label: 'South Georgia and the South Sandwich Islands', value: 'GS' },
            { label: 'Spain', value: 'ES' },
            { label: 'Sri Lanka', value: 'LK' },
            { label: 'Sudan', value: 'SD' },
            { label: 'Suriname', value: 'SR' },
            { label: 'Svalbard and Jan Mayen', value: 'SJ' },
            { label: 'Swaziland', value: 'SZ' },
            { label: 'Sweden', value: 'SE' },
            { label: 'Switzerland', value: 'CH' },
            { label: 'Syrian Arab Republic', value: 'SY' },
            { label: 'Taiwan, Province of China', value: 'TW' },
            { label: 'Tajikistan', value: 'TJ' },
            { label: 'Tanzania, United Republic of', value: 'TZ' },
            { label: 'Thailand', value: 'TH' },
            { label: 'Timor-Leste', value: 'TL' },
            { label: 'Togo', value: 'TG' },
            { label: 'Tokelau', value: 'TK' },
            { label: 'Tonga', value: 'TO' },
            { label: 'Trinidad and Tobago', value: 'TT' },
            { label: 'Tunisia', value: 'TN' },
            { label: 'Turkey', value: 'TR' },
            { label: 'Turkmenistan', value: 'TM' },
            { label: 'Turks and Caicos Islands', value: 'TC' },
            { label: 'Tuvalu', value: 'TV' },
            { label: 'Uganda', value: 'UG' },
            { label: 'Ukraine', value: 'UA' },
            { label: 'United Arab Emirates', value: 'AE' },
            { label: 'United Kingdom', value: 'GB' },
            { label: 'United States', value: 'US' },
            { label: 'United States Minor Outlying Islands', value: 'UM' },
            { label: 'Uruguay', value: 'UY' },
            { label: 'Uzbekistan', value: 'UZ' },
            { label: 'Vanuatu', value: 'VU' },
            { label: 'Venezuela', value: 'VE' },
            { label: 'Viet Nam', value: 'VN' },
            { label: 'Virgin Islands, British', value: 'VG' },
            { label: 'Virgin Islands, U.S.', value: 'VI' },
            { label: 'Wallis and Futuna', value: 'WF' },
            { label: 'Western Sahara', value: 'EH' },
            { label: 'Yemen', value: 'YE' },
            { label: 'Zambia', value: 'ZM' },
            { label: 'Zimbabwe', value: 'ZW' }
        ],

    },
    reducers: {
        setImportClientsDialog: (state, action) => {
            state.importClientsDialog = action.payload
        },
        setAddClientDialog: (state, action) => {
            state.addClientDialog = action.payload
        },
        setColumnVisibility: (state, action) => {

            const { field, hide } = action.payload || {}

            let columns = [...state.columns]
            let index = columns.findIndex(obj => obj.field == field)
            columns[index] = {
                ...columns[index],
                hide: !hide,
            }

            state.columns = columns
        },
        setAllColumnsVisibility: (state, action) => {

            const { hide } = action.payload || {}

            state.columns
                = state
                    .columns
                    .map(obj => ({
                        ...obj,
                        hide:
                            obj.hidable ?
                                hide
                                :
                                obj.hide,
                    }))

        },
        setDefaultColumnsVisibility: (state, action) => {
            state.columns
                = state
                    .columns
                    .map(obj => ({
                        ...obj,
                        hide:
                            state.defaultColumns.includes(obj.field) ?
                                false
                                :
                                true,
                    }))
        }
    },
    extraReducers: {
    },
});

export const {
    setImportClientsDialog,
    setAddClientDialog,
    setColumnVisibility,
    setAllColumnsVisibility,
    setDefaultColumnsVisibility,
} = clientsSlice.actions;

export default clientsSlice.reducer;